Models/Enums/Kind.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WhatToDo.Models.Enums
{
    public enum Kind : int
    {
        DayToDay = 0,
        Professional = 1,
        Study = 2,
        Helth = 3,
        Others = 4
    }
}

Models/Enums/Status.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WhatToDo.Models.Enums
{
    public enum Status : int
    {
        NotStarted = 0,
        Ongoing = 1,
        Done = 2
    }
}

Models/ErrorViewModel.cs
using System;

namespace WhatToDo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WhatToDo.Models.Enums;

namespace WhatToDo.Models
{
    public class ToDo
    {   
        [Key]
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime Date { get; set; } = DateTime.Now;
        public string Duration { get; set; }
        public Status Status { get; set; }
        public Kind KindOfToDo { get; set; }
        public ICollection<ToDo> List { get; set; } = new List<ToDo>();

        public ToDo()
        {
        }

        public ToDo(string name, DateTime date, string duration, Status status, Kind kindOfToDo)
        {
           
            Name = name;
            Date = date;
            Duration = duration;
            Status = status;
            KindOfToDo = kindOfToDo;
        }



        public void AddToDo(ToDo item)
        {
            List.Add(item);
        }

        public void RemoveToDo(ToDo item)
        {
            List.Add(item);
        }


        ICollection<ToDo> DoneList = new List<ToDo>();
        double totalDone = 0.00;
        public string PercentageDone(ToDo item)
        {
            if (item.Status == Status.Done)
            {
                DoneList.Add(item);
            }

            totalDone = ((DoneList.Count()) / List.Count()) * 100;


            return ("You've completed " + totalDone.ToString() + "% of your To Do List so far");

        }
               
        
    }




}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WhatToDo.Models;

namespace WhatToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Record()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ToDoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhatToDo.Data;
using WhatToDo.Models;

namespace WhatToDo.Controllers
{
    public class ToDoesController : Controller
    {
        private readonly WhatToDoContext _context;

        public ToDoesController(WhatToDoContext context)
        {
            _context = context;
        }

        // GET: ToDoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ToDo.OrderBy(item => item.Date).ToListAsync());
        }

        // GET: ToDoes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo
                .FirstOrDefaultAsync(m => m.Name == id);
            if (toDo == null)
            {
                return NotFound();
            }

            return View(toDo);
        }

        // GET: ToDoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToDoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Date,Duration,Status,KindOfToDo")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(toDo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(toDo);
        }

        // GET: ToDoes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo.FindAsync(id);
            if (toDo == null)
            {
                return NotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Date,Duration,Status,KindOfToDo")] ToDo toDo)
        {
            if (id != toDo.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoExists(toDo.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDo);
        }

        // GET: ToDoes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDo = await _context.ToDo
                .FirstOrDefaultAsync(m => m.Name == id);
            if (toDo == null)
            {
                return NotFound();
            }

            return View(toDo);
        }

        // POST: ToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var toDo = await _context.ToDo.FindAsync(id);
            _context.ToDo.Remove(toDo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoExists(string id)
        {
            return _context.ToDo.Any(e => e.Name == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "To Do List";
}

<div class="text-center">
    <h1 class="display-4">What to Do?</h1>
    <p>Trying to do my fucking first webApp</p>

    <div>
        <ul style="list-style-type: none" class="align-content-center pl-0 ml-0 font-weight-bold">
            <li>
                <label>To Dos </label>
                <input type="text" placeholder="What f** do you have to do today?" class="w-100" />
            </li>
            <li>
                <label>Activity</label>
                <input type="text" placeholder="What that s** related to?" class="w-100" />
            </li>
            <li>
                <label>Duration</label>
                <input type="text" placeholder="How long till y're f***ing done?" class="w-100" />
            </li>
        </ul>

        <p class="btn btn-dark w-100 font-weight-bold"><a asp-action="Create">Add to List</a></p>
    </div>

</div>

Views/Home/Record.cshtml
@{
    ViewData["Title"] = "Record";
}

<div class="text-center">
    <h1 class="display-4">What is my progress so far?</h1>
    <p>Here I will try to put a progress line with bar charts to show prograss day-by-day of the activities</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhatToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-check-square" aria-hidden="true"></i> | What a F** there is to Do |  </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ToDoes" asp-action="Index">To Do List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Record">Record</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WhatToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/ToDoes/Create.cshtml
@model WhatToDo.Models.ToDo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <!-- <div class="form-group">
         <label asp-for="Date" class="control-label"></label>
         <input asp-for="Date" class="form-control" />
         <span asp-validation-for="Date" class="text-danger"></span>
     </div>-->
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="NotStarted">Not Started</option>
                    <option value="Ongoing">Ongoing</option>
                    <option value="Done">Done</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KindOfToDo" class="control-label"></label>
                <select asp-for="KindOfToDo" class="form-control">
                    <option value="DayToDay">Day to Day</option>
                    <option value="Professional">Professional</option>
                    <option value="Study">Study</option>
                    <option value="Helth">Helth</option>
                    <option value="Others">Others</option>
                </select>
                <span asp-validation-for="KindOfToDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ToDoes/Delete.cshtml
@model WhatToDo.Models.ToDo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KindOfToDo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KindOfToDo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Name" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ToDoes/Details.cshtml
@model WhatToDo.Models.ToDo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KindOfToDo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KindOfToDo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Name">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ToDoes/Edit.cshtml
@model WhatToDo.Models.ToDo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <!-- <div class="form-group">
         <label asp-for="Date" class="control-label"></label>
         <input asp-for="Date" class="form-control" />
         <span asp-validation-for="Date" class="text-danger"></span>
     </div> -->
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="NotStarted">Not Started</option>
                    <option value="Ongoing">Ongoing</option>
                    <option value="Done">Done</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KindOfToDo" class="control-label"></label>
                <select asp-for="KindOfToDo" class="form-control">
                    <option value="DayToDay">Day to Day</option>
                    <option value="Professional">Professional</option>
                    <option value="Study">Study</option>
                    <option value="Helth">Helth</option>
                    <option value="Others">Others</option>
                </select>
                <span asp-validation-for="KindOfToDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ToDoes/Index.cshtml
@model IEnumerable<WhatToDo.Models.ToDo>
@using WhatToDo.Models;

@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <h1 class="display-4">What to Do?</h1>
    <p>Trying to do my fucking first webApp</p>

    <div>
        <ul style="list-style-type: none" class="align-content-center pl-0 ml-0 font-weight-bold">
            <li>
                <label>To Dos </label>
                <input type="text" placeholder="What f** do you have to do today?" class="w-100" />
            </li>
            <li>
                <label>Activity</label>
                <input type="text" placeholder="What that s** related to?" class="w-100" />
            </li>
            <li>
                <label>Duration</label>
                <input type="text" placeholder="How long till y're f***ing done?" class="w-100" />
            </li>
        </ul>

        <p class="btn btn-dark w-100 font-weight-bold"><a asp-action="Create">Add to List</a></p>
    </div>

</div>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KindOfToDo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KindOfToDo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Name">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Name">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Name">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ToDos/Index.cshtml
@model IEnumerable<WhatToDo.Models.ToDo>

@{
    ViewData["Title"] = "To Do List";
}

<h1>To Do List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
         
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>